### ISSUE TITLE
Make a tag of 0.0.1

### ISSUE THREAD

**Issue by yuichiro-naito** [belgianbeer/tzdiff#1]
I'm making FreeBSD ports Makefile and tagged version is needed to download a archives file from github.
Could you git tag 0.0.1 and push it?

**Comment by yuichiro-naito** [comment]
After tagging, I will finish making the port.
https://github.com/yuichiro-naito/ports

**Comment by belgianbeer** [comment]
Ok. I made tag as 0.1.

**Comment by yuichiro-naito** [comment]
thanks for tagging!
